### ISSUE TITLE
Collaboration request 👐

### ISSUE THREAD

**Issue by joaoofreitas** [nodejs/getting-started#19]
Hello, I would like to contribute to Node.js. 
So I'm opening this issue to ask how can I start. 

I'm open to help from [i18n](https://github.com/nodejs/TSC/blob/main/WORKING_GROUPS.md#i18n) to [Streams Working Group](https://github.com/nodejs/readable-stream/blob/master/README.md#streams-working-group). Whatever it's needed.

Waiting for your response.
Best regards

**Comment by mcollina** [comment]
Check out https://www.nodetodo.org/, it teaches how to get started. As for streams issues, I would recommend you to take a look at https://github.com/nodejs/node/issues?q=is%3Aissue+is%3Aopen+streams if there are things you could help solving. Happy to review PRs (tag me or @nodejs/streams)
