### ISSUE TITLE
Is this a CommComm managed repo?

### ISSUE THREAD

**Issue by jasnell** [nodejs/getting-started#6]
In the README, it is not clear if this is a CommComm managed repo or a TSC managed repo. It would be great if that can be clarified and made obvious in the README. thank you!

**Comment by bnb** [comment]
@jasnell This is a jointly managed repo, as I understand it. @hackygolucky may have more insight to share on the details 😄

**Comment by hackygolucky** [comment]
It needs to be updated in the readme of this repo, but it is listed in the
admin repo as a joint group.

**Comment by bnb** [comment]
README.md was updated to appropriately reflect this in #15 ❤️
