### ISSUE TITLE
I'd like to contribute to the Website WG

### ISSUE THREAD

**Issue by rossijonas** [nodejs/getting-started#9]
Thank you for giving a minute of attention!

I'd like to apply to contribute to Website WG. I'm studying web development online since a year ago and, I am a student of System's Analysys and Development at a University in Brazil since july 2017. (It's a Second Graduation (I'm already a Civil Engineer 2005, and MBA 2010).
I'm looking for a open source project that I can keep contributing and to feel proud of!
Node.js is something that I'm loving each time more and more, and I guess until this moment I have some skills that allows me to contribute on Website WG.
I hope I can fit! 

✌️Thank you!

**Comment by ghost** [comment]
cc @nodejs/website

**Comment by chris--young** [comment]
Sounds great

I'd recommend keeping an eye on issues with the `good first issue` label in both the https://github.com/nodejs/nodejs.org and https://github.com/nodejs/node repos for a place to get started. Feel free to reach out if you're looking for some guidance (my email is on my profile).

**Comment by rossijonas** [comment]
@chris--young Thank you very much! I'll go read the guidelines / setup repo on my computer / start to check where I could help... and then I'll email you telling the solution I thought for the issue ... just to get your opinion. Thanks! I'm excited to do this! ✌️

**Comment by fhemberger** [comment]
@rossijonas If you have any questions regarding the website repo, I'd be glad to help you as well.

**Comment by rossijonas** [comment]
Thank you very much @fhemberger!!
